using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;

namespace CreatureSpeedPatcher;

public static class Program
{
    private static Lazy<Settings> _settings = null!;

    public static Task<int> Main(string[] args) => SynthesisPipeline.Instance
        .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
        .SetAutogeneratedSettings("Settings", "settings.json", out _settings)
        .SetTypicalOpen(GameRelease.SkyrimSE, "CreatureSpeedPatcher.esp")
        .Run(args);

    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        Patcher.Run(state.LoadOrder.PriorityOrder.Npc().WinningOverrides(includeDeletedRecords: true),
            state.LinkCache, state.PatchMod, _settings.Value, Console.Error);
        Console.Error.Flush();
    }
}
